version: "~> 1.0"
language: node_js
node_js:
- 8.16.2
install:
- npm install -g codecov
before_script:
- npm install
script:
- npm run clean
- npm run build-typescript
- npm run build-storybook
- npm run coverage
- codecov --disable=gcov
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: ag+1CWETtLndl9KBxHpgo3ZjDq+H3vDcwLlKJgjQTV/La1R0xUopNjnYe7xRlkklyZzkzUvf4tFX7yQnb6KJlsee1NblS4yXd5G8dQ1ipBKQutj8kQyMANDuoMbRtGqZJ2tsUdxw/O82i53W4diip/HWRi6jiFuxKIvjMEWvfZZ5ML9JsD84D4g+pxQ7qd7/pXkquxquY3HtLJUYj7WDvfl/wJQxHfTOuA2gHsp6Juad6/Te7sbT8pidzbL4brVB/Kx4+4aThqigcE7A6qWWQXzzN0i3H/DZf60ALMpZs1QpEE6nenCN2KMgQdMKoKYormVCR2b0YybfU6GqUSzwV8gQcMQZuUZmGSDUrdUPsTqGLR1nQzw0nkOIT/IhGzfSsFJUB2jZVDhhQrM6nmFAb9ggrYKlim32l/DqZYWbiquZayYQOC1DiXzjSjBJldVuXqSWoRJHE4qqpzLpAnjggp/gD2W1EWPZLcLGbJI+D0ghMXyL/Wam4/2ppeah1N3h14rC98mF9MgGaFqodFqGNmxLUwruQVDe2YqwTQsuq5DKs93EKewaOBvF28ZsWand13iZVyF+ZcT82fbdKTw8M0IQ95/92sfwz8BwElcttNb24dH0yqd5P+4ngMyAa4H6cFdiolJzeQ/IsQvrtb391D0qZzdxeOVZJsqRDJDscTU=
